# Generated by Django 4.2.7 on 2023-11-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=100)),
                ('authorname', models.CharField(max_length=100)),
                ('currentlycheckedout', models.CharField(max_length=50)),
                ('numberoftimescheckedout', models.IntegerField()),
            ],
        ),
    ]
