# Generated by Django 4.2.7 on 2023-12-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreservation', '0002_bookdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('book', models.CharField(max_length=100)),
            ],
        ),
    ]
